########################################
# Constants
########################################
uint8 OFF = 0
uint8 ONCE = 1
uint8 REPEAT = 2

########################################
# Request
########################################
uint8 mode
float32 cycle_time 1.0  # sec
---
########################################
# Response
########################################
bool success
string message
